server:
  port: 5000
spring:
  application:
    name: projecto
  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/projecto
    url: jdbc:mysql://projectodb.cdewg46msbic.us-east-1.rds.amazonaws.com:3306/projectodb
    username: root
    password: Matt0038!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true